# Generated by Django 5.1.2 on 2024-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'brands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('transmission', models.CharField(max_length=20)),
                ('engine_volume', models.CharField(max_length=250)),
                ('drive', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('power_volume', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cars',
                'managed': False,
            },
        ),
    ]
