# Generated by Django 5.1.4 on 2024-12-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='buy_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='sell_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
