# Generated by Django 5.1.4 on 2024-12-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Телефон')),
                ('content', models.TextField(max_length=200, verbose_name='Сообщение')),
                ('privacy_policy_agreed', models.BooleanField(default=False, verbose_name='Согласие с политикой конфиденциальности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
        ),
    ]
