# Generated by Django 5.1.4 on 2025-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Рейтинг компании')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('review_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата отзыва')),
            ],
        ),
    ]
