# Generated by Django 5.1.4 on 2025-01-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrating',
            name='company_name',
            field=models.CharField(default='Tomiko Trade', max_length=255, unique=True),
        ),
    ]
