# Generated by Django 5.1.4 on 2025-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_parser', '0002_companyrating_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrating',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='companyrating',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
